// <auto-generated />
using System;
using HighPerformanceTariffsAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HighPerformanceTariffsAPI.Infrastructure.Migrations
{
    [DbContext(typeof(TariffsDbContext))]
    [Migration("20251110203352_TransformToCurrencyPairs")]
    partial class TransformToCurrencyPairs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HighPerformanceTariffsAPI.Domain.Entities.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("TargetCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency")
                        .HasDatabaseName("IX_Tariffs_BaseCurrency");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Tariffs_IsActive");

                    b.HasIndex("BaseCurrency", "IsActive")
                        .HasDatabaseName("IX_Tariffs_BaseCurrency_IsActive");

                    b.HasIndex("EffectiveDate", "IsActive")
                        .HasDatabaseName("IX_Tariffs_EffectiveDate_IsActive");

                    b.ToTable("Tariffs");
                });
#pragma warning restore 612, 618
        }
    }
}
